# Generated by Django 4.1.7 on 2023-07-20 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0007_profile_birth_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='first_name1',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='profile',
            name='last_name1',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
