# Generated by Django 4.1.7 on 2023-07-17 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0007_profile_birth_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='nick',
            field=models.CharField(blank=True, max_length=250, verbose_name='Никнейм'),
        ),
    ]
